name: Question
description: Ask a question about usage, configuration, or troubleshooting
title: "[Question]: "
labels: ["question", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        **Before asking, please check:**
        - [Documentation](https://github.com/NVIDIA/cloud-native-stack/tree/main/docs)
        - [Existing issues](https://github.com/NVIDIA/cloud-native-stack/issues?q=is%3Aissue)
        - [Discussions](https://github.com/NVIDIA/cloud-native-stack/discussions)

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I searched existing issues and discussions
          required: true
        - label: I checked the documentation
          required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know? Be as specific as possible.
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Installation / Deployment
        - CLI usage (cnsctl)
        - API usage (cnsd)
        - Recipe configuration
        - Bundler output / Helm values
        - Troubleshooting errors
        - Performance / Monitoring
        - Integration with other tools
        - Best practices
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Relevant details about your setup. Redact any credentials or secrets.
      placeholder: |
        - What you're trying to accomplish:
        - CNS version (`cnsctl version`):
        - Platform (eks/gke/aks/self-managed):
        - Kubernetes version:
        - GPU type (if applicable):
        - Commands you ran:
        - Output / errors:
    validations:
      required: false

  - type: textarea
    id: attempts
    attributes:
      label: What have you tried?
      description: List any approaches or workarounds you've already attempted.
    validations:
      required: false